# Generated by Django 5.2 on 2025-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_conversation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
