# Generated by Django 5.2 on 2025-12-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_edited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="conversation_history",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
